# Generated by Django 4.2.30 on 2026-06-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("customers", "0001_initial"),
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("pickup_city", models.CharField(max_length=200)),
                ("pickup_address", models.TextField()),
                ("preferred_pickup_date", models.DateField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=1)),
                ("dimensions", models.CharField(blank=True, max_length=200)),
                ("estimated_weight", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("contacted", "Contacté"),
                            ("confirmed", "Confirmé"),
                            ("pickup_scheduled", "Ramassage planifié"),
                            ("received", "Reçu"),
                            ("loaded", "Chargé"),
                            ("in_transit", "En route"),
                            ("arrived_cameroon", "Arrivé au Cameroun"),
                            ("delivered", "Livré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("customer_notes", models.TextField(blank=True)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="customers.customer",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.destinationcity",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.servicetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportRequestPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="request_photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="logistics.transportrequest",
                    ),
                ),
            ],
        ),
    ]
