# Generated by Django 4.2.30 on 2026-06-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transportrequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
