# Generated by Django 4.2.30 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_transportrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('pickup_scheduled', 'Pickup scheduled'), ('received', 'Received'), ('loaded', 'Loaded'), ('in_transit', 'In transit'), ('arrived_cameroon', 'Arrived in Cameroon'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=30),
        ),
    ]
