# Generated by Django 4.2.30 on 2026-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_transportrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
