# Generated by Django 4.2.30 on 2026-06-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_requestcomment'),
        ('logistics', '0004_requeststatusevent'),
        ('logistics', '0004_transportrequest_amount_paid_and_more'),
    ]

    operations = [
    ]
