# Generated by Django 4.2.30 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_customernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='target_type',
            field=models.CharField(choices=[('all', 'All'), ('region', 'Region'), ('request_status', 'Request status')], max_length=50),
        ),
    ]
