# Generated by Django 4.2.30 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerule',
            name='unit',
            field=models.CharField(blank=True, help_text="Example: 'piece', 'm³', 'vehicle'", max_length=50),
        ),
    ]
