# SAHA-STL dedicated Redis instance
bind 127.0.0.1 ::1
protected-mode yes
port 6383
requirepass 7e586a806840196aec61151d47b3d458dc6f5e1980839db0
dir /home/mignon/saha/deploy/redis-data
pidfile /home/mignon/saha/deploy/redis-data/redis-saha.pid
logfile ""
appendonly no
save 900 1
save 300 10
save 60 10000
daemonize no
